apiVersion: apps/v1
kind: Deployment
metadata:
  name: literate-giggle
  namespace: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabliterate-giggle: literate-giggle
  template:
    metadata:
      labeliterate-giggle: literate-giggle
    spec:
      containers:
      - name: literate-giggle
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: ENVIRONMENT
          value: {{ .Values.environment }}