apiVersion: v1
kind: Service
metadata:
  name: literate-giggle-service
  namespace: {{ .Values.environment }}
spec:
  selector:
    app: literate-giggle
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}