global:
  imagePullSecrets: []
  namespace: default

services:
  gateway:
    enabled: true
    image:
      repository: roxane451/literate-giggle-gateway
      tag: latest
      pullPolicy: IfNotPresent
    port: 8080
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    envFromSecret: gateway-secret

  orders:
    enabled: true
    image:
      repository: roxane451/literate-giggle-orders
      tag: latest
      pullPolicy: IfNotPresent
    port: 8081
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8081
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    envFromSecret: orders-secret

  users:
    enabled: true
    image:
      repository: roxane451/literate-giggle-users
      tag: latest
      pullPolicy: IfNotPresent
    port: 8082
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8082
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    envFromSecret: users-secret

# Secret configuration used by templates
gateway:
  secretKey: ""
  usersServiceUrl: "http://users:8082"
  ordersServiceUrl: "http://orders:8081"
users:
  databaseUrl: "sqlite://db.sqlite3"
orders:
  databaseUrl: "sqlite://db.sqlite3"

# Configuration ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: dev.literate-giggle.local
      paths:
        - path: /
          pathType: Prefix
  tls: []