{{- if .Values.services.gateway.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.gateway.secretKey | default "REPLACE_ME" }}"
  USERS_SERVICE_URL: "{{ .Values.gateway.usersServiceUrl | default "http://users:8082" }}"
  ORDERS_SERVICE_URL: "{{ .Values.gateway.ordersServiceUrl | default "http://orders:8081" }}"
---
{{- end }}

{{- if .Values.services.users.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.users.databaseUrl | default "sqlite://db.sqlite3" }}"
---
{{- end }}

{{- if .Values.services.orders.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-orders-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.orders.databaseUrl | default "sqlite://db.sqlite3" }}"
---
{{- end }}